### ISSUE TITLE
inside createmsg function give list of available usernames main.js 179 socket.js 4

### ISSUE THREAD

**Issue by barium-bromide** [ddddddddrrdd3/Chat#14]

**Comment by barium-bromide** [comment]
if (currentRoom === roomId) createMsg(id, authorName, content, time);

**Comment by barium-bromide** [comment]
function createMsg(id, authorName, content, time) {
    let date = new Date(time);

    let container = document.createElement("div");
    container.className = "container";

    let name = document.createElement("h5");
    name.innerText = authorName;

    let msg = document.createElement("p");
    msg.innerText = content;
    msg.innerHTML = msg.innerHTML.replace(`@${Username}`,`<span class="mention">@${Username}</span>`);

    let clock = document.createElement("span");
    clock.className = "time";
    clock.innerText =
        String(date.getDate()) +
        "/" +
        String(date.getMonth() + 1) +
        "/" +
        String(date.getFullYear()) +
        " " +
        date.toLocaleTimeString().slice(0, -6) +
        (date.getHours() > 11 ? " PM" : " AM");

    container.appendChild(name);
    container.appendChild(msg);
    container.appendChild(clock);
    container.id = id;

    outerWrap.appendChild(container);

    if (id == "SYSTEM") {
        container.classList.add("system-colour");
        clock.classList.add("system-colour");
        setTimeout(() => {
            outerWrap.removeChild(container);
        }, 2000);
    }
}

**Comment by Mortis66666** [comment]
I have a few questions

1. Is the one behind @ username and not display name?
2. Must the username also change its colour, despite it's not the user's username?
3. Should the text behind @ change colour, whether the text is a valid username or not?

**Comment by barium-bromide** [comment]
1. You are right, i should put display name which means you need to send username and display name to me
2. whenever someone @mention somebody, the @mention colour will display to everyone, this is to show that this user exist but to the user who are being mention, I might have to change the colour of the textbox to show more clearer, therefore need some adjustment
3. if not a valid username it wont change therefore i might need to adjust the code with some if else
